### ISSUE TITLE
Importing plugin url_handlers.py failed: name 're' is not defined

### ISSUE THREAD

**Issue by saveman71** [JAugusto42/terminator#5]
Thank you so much for the fork!

I come from https://bugs.archlinux.org/index.php?do=details&task_id=65788&action=details.add_notification&ids=65788&user_id=24693 and I was looking to replace my current terminator with yours as I'm an heavy user of URL highlighting and custom plugins.

However it seems the builtin plugin `url_handlers.py` doesn't load on my Arch. It still works but opens a "default" config terminator.

![Screenshot from 2020-03-12 11-11-54](https://user-images.githubusercontent.com/1615426/76510734-63a3da80-6452-11ea-8d6f-797af2bcd886.png)

I also tried to duplicate my old config and disable all the plugins, but the error is till there:

```
./terminator -g ~/.config/terminator-python3/config

(terminator:142051): VTE-WARNING **: 11:11:41.875: (../vte/src/vtegtk.cc:2171):int vte_terminal_match_add_regex(VteTerminal*, VteRegex*, guint32): runtime check failed: (_vte_regex_has_multiline_compile_flag(regex))

(terminator:142051): VTE-WARNING **: 11:11:41.875: (../vte/src/vtegtk.cc:2171):int vte_terminal_match_add_regex(VteTerminal*, VteRegex*, guint32): runtime check failed: (_vte_regex_has_multiline_compile_flag(regex))

(terminator:142051): VTE-WARNING **: 11:11:41.875: (../vte/src/vtegtk.cc:2171):int vte_terminal_match_add_regex(VteTerminal*, VteRegex*, guint32): runtime check failed: (_vte_regex_has_multiline_compile_flag(regex))

(terminator:142051): VTE-WARNING **: 11:11:41.875: (../vte/src/vtegtk.cc:2171):int vte_terminal_match_add_regex(VteTerminal*, VteRegex*, guint32): runtime check failed: (_vte_regex_has_multiline_compile_flag(regex))

(terminator:142051): VTE-WARNING **: 11:11:41.875: (../vte/src/vtegtk.cc:2171):int vte_terminal_match_add_regex(VteTerminal*, VteRegex*, guint32): runtime check failed: (_vte_regex_has_multiline_compile_flag(regex))
PluginRegistry::load_plugins: Importing plugin url_handlers.py failed: name 're' is not defined
```

My config:

```
[global_config]
  enabled_plugins = InactivityWatch, EditorPlugin, LaunchpadCodeURLHandler, APTURLHandler, LaunchpadBugURLHandler
  inactive_color_offset = 1.0
[keybindings]
  broadcast_all = None
  edit_tab_title = None
  go_down = None
  go_left = None
  go_next = None
  go_prev = None
  go_right = None
  go_up = None
  help = None
  hide_window = None
  toggle_scrollbar = None
[layouts]
  [[default]]
    [[[child1]]]
      parent = window0
      type = Terminal
    [[[window0]]]
      parent = ""
      type = Window
[plugins]
  [[EditorPlugin]]
    command = /usr/bin/subl3 {filepath}{:line}{:column}
    groups = file line column
    match = '''(?:a/|b/)?([^ \t\n\r\f\v\"'─│:*()\[\]]+?/[^ \t\n\r\f\v\"'─│:*()\[\]]+\.\w+)(?::([0-9]+))?(?::([0-9]+))?'''
[profiles]
  [[default]]
    background_color = "#263238"
    background_darkness = 0.96
    background_type = transparent
    cursor_color = "#aaaaaa"
    font = Monospace 11
    foreground_color = "#ffffff"
    scrollback_infinite = True
    show_titlebar = False
    use_system_font = False
```

(this is the full config, but I can also reproduce without any plugins loaded, and I know I would have to convert my personal plugin to python3 at some point, but I'm stuck earlier :))

**Comment by JAugusto42** [comment]
Hi, thanks for using this fork.
I reproduce the error here, as soon as possible a correction comes out.

**Comment by JAugusto42** [comment]
I think you can test now, I tested it here and everything seemed fine

**Comment by JAugusto42** [comment]
i test here again and the problem was not solving here, i looking it right now.

**Comment by JAugusto42** [comment]
I realized that json was a better format, so I incorporated a modification made in another fork giving credit. Now you just need to adapt your config to json format and the file name remains the same, just config. I hope this works for you.

**Comment by saveman71** [comment]
Thank you for the fix. Now I have

```
PluginRegistry::load_plugins: Importing plugin editor_plugin.py failed: 'str' object has no attribute 'decode'
```

Do you have it as well?

**Comment by saveman71** [comment]
Seems like it could be https://github.com/JAugusto42/terminator/blob/6cc2974f71b04e7a18b1eff0b93b8dbfe85f647a/terminatorlib/terminal.py#L1101

**Comment by saveman71** [comment]
Aaah, sorry that's my plugin!

**Comment by JAugusto42** [comment]
haha ok
